import Head from "next/head";
import ProductsList from "../components/ProductsList";
import Slider from "../components/Slider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Shopestoon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Slider />
        <ProductsList />
      </div>
    </>
  );
}
